### ISSUE TITLE
[Question] rpc error: code = Unavailable desc = transport is closing, status: <nil>

### ISSUE THREAD

**Issue by qii67** [Hyperledger-TWGC/tape#157]
***Update
I found the tape invoke my chaincode successfully in dev_* container, but after that output the error `rpc error: code = Unavailable desc = transport is closing, status: <nil>`

the complete output is as follows:
```
fabric@ubuntu:/fabric1.4/fabric-samples/first-network$ docker run --name tape -e TAPE_LOGLEVEL=debug --network host -v $PWD:/config guoger/tape tape --config=/config/tapeconfig.yaml --number=10
time="2021-03-13T06:05:28Z" level=info msg="Will use rate 0.000000 as send rate\n"
time="2021-03-13T06:05:28Z" level=info msg="Will use 824639007536 as burst\n"
time="2021-03-13T06:05:28Z" level=info msg="Start sending transactions."
time="2021-03-13T06:05:28Z" level=debug msg="Start sending broadcast"
time="2021-03-13T06:05:28Z" level=debug msg="Start sending broadcast"
time="2021-03-13T06:06:48Z" level=error msg="recv broadcast err: rpc error: code = Unavailable desc = transport is closing, status: <nil>\n"
time="2021-03-13T06:06:48Z" level=error msg="recv broadcast err: rpc error: code = Unavailable desc = transport is closing, status: <nil>\n"

```
what should i do to get the evaluation result?

PS: tape version: latest; Hyperledger Fabric: v.1.4.3

I am trying to use tape to evaluate my chaincode. My command is `docker run --name tape -e TAPE_LOGLEVEL=debug --network host -v $PWD:/config guoger/tape tape --config=/config/config.yaml --number=10`，but i got the output:

> fabric@ubuntu:/fabric1.4/fabric-samples/first-network$ docker run --name tape -e TAPE_LOGLEVEL=debug --network host -v $PWD:/config guoger/tape tape --config=/config/config.yaml --number=10
time="2021-03-11T02:30:45Z" level=info msg="Will use rate 0.000000 as send rate\n"
time="2021-03-11T02:30:45Z" level=info msg="Will use 824634829584 as burst\n"
time="2021-03-11T02:30:45Z" level=error msg="error connecting to localhost:7051: failed to load client certificate: tls: private key does not match public key"

My config.yame is as follows:
```
# Definition of nodes 
peer1: &peer1 
  addr: localhost:7051 
  tls_ca_cert: /config/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem 
  tls_ca_key: /config/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key 
  tls_ca_root: /config/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt 
 
peer3: &peer3 
  addr: localhost:8051 
  tls_ca_cert: /config/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem 
#  tls_ca_key: /config/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/server.key 
#  tls_ca_root: /config/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/server.crt 
 
peer2: &peer2 
  addr: localhost:9051
  tls_ca_cert: /config/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem
#  tls_ca_key: /config/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/server.key
#  tls_ca_root: /config/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/server.crt

peer4: &peer4
  addr: localhost:10051
  tls_ca_cert: /config/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem
#  tls_ca_key: /config/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls/server.key
#  tls_ca_root: /config/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls/server.crt

orderer1: &orderer1
  addr: localhost:7050
  tls_ca_cert: /config/crypto-config/ordererOrganizations/example.com/msp/tlscacerts/tlsca.example.com-cert.pem
#  tls_ca_key: /config/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key
#  tls_ca_root: /config/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
# Nodes to interact with
endorsers:
  - *peer1
  - *peer2
#  - *peer3
#  - *peer4
# we might support multi-committer in the future for more complex test scenario,
# i.e. consider tx committed only if it's done on >50% of nodes. But for now,
# it seems sufficient to support single committer.
committer: *peer2
orderer: *orderer1

# Invocation configs
channel: mychannel
chaincode: automaster_kv 
args:
  - querykv
  - 5563357532700333105087925631153292765099644740791189185:4305923957050798362229080326563977167165357342001938654
  - user1
  - enc
mspid: Org1MSP
private_key: /config/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/029e6f199d81a1de05811bcadd60a0ab0ac117198ce0d4d05ef859d2f568bcfd_sk
sign_cert: /config/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem
num_of_conn: 2
client_per_conn: 2

```

My fabric version is 1.4.3, the network use the [byfn](https://hyperledger-fabric.readthedocs.io/en/release-1.4/build_network.html) network with 2 orgs, 2 peers per org, and the crypto-config directory is as follow:
```
crypto-config
├── ordererOrganizations
│   └── example.com
│       ├── ca
│       │   ├── 33f37c1eac5f7969dbd379bdf571b34f467d4b07e7f5e0aa919684c8e14f5810_sk
│       │   └── ca.example.com-cert.pem
│       ├── msp
│       │   ├── admincerts
│       │   ├── cacerts
│       │   │   └── ca.example.com-cert.pem
│       │   ├── config.yaml
│       │   └── tlscacerts
│       │       └── tlsca.example.com-cert.pem
│       ├── orderers
│       │   ├── orderer2.example.com
│       │   │   ├── msp
│       │   │   │   ├── admincerts
│       │   │   │   ├── cacerts
│       │   │   │   │   └── ca.example.com-cert.pem
│       │   │   │   ├── config.yaml
│       │   │   │   ├── keystore
│       │   │   │   │   └── 513d9fb8a5787db7898897820c2d4df39798589773827c70329a42c0d460a5fc_sk
│       │   │   │   ├── signcerts
│       │   │   │   │   └── orderer2.example.com-cert.pem
│       │   │   │   └── tlscacerts
│       │   │   │       └── tlsca.example.com-cert.pem
│       │   │   └── tls
│       │   │       ├── ca.crt
│       │   │       ├── server.crt
│       │   │       └── server.key
│       │   ├── orderer3.example.com
│       │   │   ├── msp
│       │   │   │   ├── admincerts
│       │   │   │   ├── cacerts
│       │   │   │   │   └── ca.example.com-cert.pem
│       │   │   │   ├── config.yaml
│       │   │   │   ├── keystore
│       │   │   │   │   └── 7aa744567533f892af8106e81e3e16a76eeb36d5561762e682353df53dc6a44d_sk
│       │   │   │   ├── signcerts
│       │   │   │   │   └── orderer3.example.com-cert.pem
│       │   │   │   └── tlscacerts
│       │   │   │       └── tlsca.example.com-cert.pem
│       │   │   └── tls
│       │   │       ├── ca.crt
│       │   │       ├── server.crt
│       │   │       └── server.key
│       │   ├── orderer4.example.com
│       │   │   ├── msp
│       │   │   │   ├── admincerts
│       │   │   │   ├── cacerts
│       │   │   │   │   └── ca.example.com-cert.pem
│       │   │   │   ├── config.yaml
│       │   │   │   ├── keystore
│       │   │   │   │   └── c0dca298749ff210a92e2545c6a78fbe569dc8f59ee3dc0cef7786d9e6f1d92c_sk
│       │   │   │   ├── signcerts
│       │   │   │   │   └── orderer4.example.com-cert.pem
│       │   │   │   └── tlscacerts
│       │   │   │       └── tlsca.example.com-cert.pem
│       │   │   └── tls
│       │   │       ├── ca.crt
│       │   │       ├── server.crt
│       │   │       └── server.key
│       │   ├── orderer5.example.com
│       │   │   ├── msp
│       │   │   │   ├── admincerts
│       │   │   │   ├── cacerts
│       │   │   │   │   └── ca.example.com-cert.pem
│       │   │   │   ├── config.yaml
│       │   │   │   ├── keystore
│       │   │   │   │   └── bd16a384f2a80b6ea396066a45723ca88f1e6339dc69f2c1ae4cff7cd67a292b_sk
│       │   │   │   ├── signcerts
│       │   │   │   │   └── orderer5.example.com-cert.pem
│       │   │   │   └── tlscacerts
│       │   │   │       └── tlsca.example.com-cert.pem
│       │   │   └── tls
│       │   │       ├── ca.crt
│       │   │       ├── server.crt
│       │   │       └── server.key
│       │   └── orderer.example.com
│       │       ├── msp
│       │       │   ├── admincerts
│       │       │   ├── cacerts
│       │       │   │   └── ca.example.com-cert.pem
│       │       │   ├── config.yaml
│       │       │   ├── keystore
│       │       │   │   └── 74fe313274ddd59b8b06d61a0784f90bdd5572785feb3753a2aca54271498770_sk
│       │       │   ├── signcerts
│       │       │   │   └── orderer.example.com-cert.pem
│       │       │   └── tlscacerts
│       │       │       └── tlsca.example.com-cert.pem
│       │       └── tls
│       │           ├── ca.crt
│       │           ├── server.crt
│       │           └── server.key
│       ├── tlsca
│       │   ├── 50f9cc70872afda0f62d8c06253357672d3ecf40125673be00368d10d78b99d4_sk
│       │   └── tlsca.example.com-cert.pem
│       └── users
│           └── Admin@example.com
│               ├── msp
│               │   ├── admincerts
│               │   ├── cacerts
│               │   │   └── ca.example.com-cert.pem
│               │   ├── config.yaml
│               │   ├── keystore
│               │   │   └── 839529ccc5b116e08ac5de80f4fcdda22ce03a69a0b827692e35d8b672386070_sk
│               │   ├── signcerts
│               │   │   └── Admin@example.com-cert.pem
│               │   └── tlscacerts
│               │       └── tlsca.example.com-cert.pem
│               └── tls
│                   ├── ca.crt
│                   ├── client.crt
│                   └── client.key
└── peerOrganizations
    ├── org1.example.com
    │   ├── ca
    │   │   ├── c721929a46287dbd3ce25b253bf10ec2d9879420056ff55f6ae8544028942952_sk
    │   │   └── ca.org1.example.com-cert.pem
    │   ├── msp
    │   │   ├── admincerts
    │   │   ├── cacerts
    │   │   │   └── ca.org1.example.com-cert.pem
    │   │   ├── config.yaml
    │   │   └── tlscacerts
    │   │       └── tlsca.org1.example.com-cert.pem
    │   ├── peers
    │   │   ├── peer0.org1.example.com
    │   │   │   ├── msp
    │   │   │   │   ├── admincerts
    │   │   │   │   ├── cacerts
    │   │   │   │   │   └── ca.org1.example.com-cert.pem
    │   │   │   │   ├── config.yaml
    │   │   │   │   ├── keystore
    │   │   │   │   │   └── 25acc7d752fa67ed6236daedaa6d74324b61d63c9ad44abe350343aefa0cdda6_sk
    │   │   │   │   ├── signcerts
    │   │   │   │   │   └── peer0.org1.example.com-cert.pem
    │   │   │   │   └── tlscacerts
    │   │   │   │       └── tlsca.org1.example.com-cert.pem
    │   │   │   └── tls
    │   │   │       ├── ca.crt
    │   │   │       ├── server.crt
    │   │   │       └── server.key
    │   │   └── peer1.org1.example.com
    │   │       ├── msp
    │   │       │   ├── admincerts
    │   │       │   ├── cacerts
    │   │       │   │   └── ca.org1.example.com-cert.pem
    │   │       │   ├── config.yaml
    │   │       │   ├── keystore
    │   │       │   │   └── 1acc21e929e01d6f47abc9a81f1a1b2dcb1233e9f091c3b7df0d25ab7d949e19_sk
    │   │       │   ├── signcerts
    │   │       │   │   └── peer1.org1.example.com-cert.pem
    │   │       │   └── tlscacerts
    │   │       │       └── tlsca.org1.example.com-cert.pem
    │   │       └── tls
    │   │           ├── ca.crt
    │   │           ├── server.crt
    │   │           └── server.key
    │   ├── tlsca
    │   │   ├── 263b89eacb6be56ab86de14819761eb0caa0a8fed8e48349a20cc9ddad52921b_sk
    │   │   └── tlsca.org1.example.com-cert.pem
    │   └── users
    │       ├── Admin@org1.example.com
    │       │   ├── msp
    │       │   │   ├── admincerts
    │       │   │   ├── cacerts
    │       │   │   │   └── ca.org1.example.com-cert.pem
    │       │   │   ├── config.yaml
    │       │   │   ├── keystore
    │       │   │   │   └── 983b4b98e6e6f26a119fa696759f2b46860ddd2aad38c619554658ac9fe3cb4a_sk
    │       │   │   ├── signcerts
    │       │   │   │   └── Admin@org1.example.com-cert.pem
    │       │   │   └── tlscacerts
    │       │   │       └── tlsca.org1.example.com-cert.pem
    │       │   └── tls
    │       │       ├── ca.crt
    │       │       ├── server.crt
    │       │       └── server.key
    │       └── User1@org1.example.com
    │           ├── msp
    │           │   ├── admincerts
    │           │   ├── cacerts
    │           │   │   └── ca.org1.example.com-cert.pem
    │           │   ├── config.yaml
    │           │   ├── keystore
    │           │   │   └── 029e6f199d81a1de05811bcadd60a0ab0ac117198ce0d4d05ef859d2f568bcfd_sk
    │           │   ├── signcerts
    │           │   │   └── User1@org1.example.com-cert.pem
    │           │   └── tlscacerts
    │           │       └── tlsca.org1.example.com-cert.pem
    │           └── tls
    │               ├── ca.crt
    │               ├── client.crt
    │               └── client.key
    └── org2.example.com
        ├── ca
        │   ├── ca.org2.example.com-cert.pem
        │   └── d38fc4cf9eca6afbda1b3a0c4e18661c7bf8959cb6dd61529f0903a87cfd29b8_sk
        ├── msp
        │   ├── admincerts
        │   ├── cacerts
        │   │   └── ca.org2.example.com-cert.pem
        │   ├── config.yaml
        │   └── tlscacerts
        │       └── tlsca.org2.example.com-cert.pem
        ├── peers
        │   ├── peer0.org2.example.com
        │   │   ├── msp
        │   │   │   ├── admincerts
        │   │   │   ├── cacerts
        │   │   │   │   └── ca.org2.example.com-cert.pem
        │   │   │   ├── config.yaml
        │   │   │   ├── keystore
        │   │   │   │   └── 817b1635046a103f4756e32cd6ef373feb1a193f1ceaf4965eda0c82378cfe28_sk
        │   │   │   ├── signcerts
        │   │   │   │   └── peer0.org2.example.com-cert.pem
        │   │   │   └── tlscacerts
        │   │   │       └── tlsca.org2.example.com-cert.pem
        │   │   └── tls
        │   │       ├── ca.crt
        │   │       ├── server.crt
        │   │       └── server.key
        │   └── peer1.org2.example.com
        │       ├── msp
        │       │   ├── admincerts
        │       │   ├── cacerts
        │       │   │   └── ca.org2.example.com-cert.pem
        │       │   ├── config.yaml
        │       │   ├── keystore
        │       │   │   └── 0a8b34b681d0f27057a9faf05063874882faf4a6a225215d1be83b7fbea0bfff_sk
        │       │   ├── signcerts
        │       │   │   └── peer1.org2.example.com-cert.pem
        │       │   └── tlscacerts
        │       │       └── tlsca.org2.example.com-cert.pem
        │       └── tls
        │           ├── ca.crt
        │           ├── server.crt
        │           └── server.key
        ├── tlsca
        │   ├── 490df712b215769cab765b1725fdf431ceae9727a7076c8788d8c48b4e79ec2a_sk
        │   └── tlsca.org2.example.com-cert.pem
        └── users
            ├── Admin@org2.example.com
            │   ├── msp
            │   │   ├── admincerts
            │   │   ├── cacerts
            │   │   │   └── ca.org2.example.com-cert.pem
            │   │   ├── config.yaml
            │   │   ├── keystore
            │   │   │   └── ef026cbf868ef433bb8c88491d0c287882fbd4ae33cb1f761921d791d6a458bb_sk
            │   │   ├── signcerts
            │   │   │   └── Admin@org2.example.com-cert.pem
            │   │   └── tlscacerts
            │   │       └── tlsca.org2.example.com-cert.pem
            │   └── tls
            │       ├── ca.crt
            │       ├── server.crt
            │       └── server.key
            └── User1@org2.example.com
                ├── msp
                │   ├── admincerts
                │   ├── cacerts
                │   │   └── ca.org2.example.com-cert.pem
                │   ├── config.yaml
                │   ├── keystore
                │   │   └── 526712fdb63fa2b7fc06cd4fbcb4268f83f5f9d1012e00cce8e4ea21b553cd41_sk
                │   ├── signcerts
                │   │   └── User1@org2.example.com-cert.pem
                │   └── tlscacerts
                │       └── tlsca.org2.example.com-cert.pem
                └── tls
                    ├── ca.crt
                    ├── client.crt
                    └── client.key
```

Could you plz help me to solve this problem? Thanks a lot!   @SamYuan1990
