### ISSUE TITLE
rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: "too_many_pings"root

### ISSUE THREAD

**Issue by ygzhang-yolo** [Hyperledger-TWGC/tape#273]
I'm trying to use docker to exec the tape, but got this error:
```bash
$ docker run --net=host -v $PWD:/config ghcr.io/hyperledger-twgc/tape tape -c /config/config.yaml -n 100
2022/09/29 07:55:28 debug logging disabled
2022/09/29 07:55:28 debug logging disabled
For FAQ, please check https://github.com/Hyperledger-TWGC/tape/wiki/FAQ
rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: "too_many_pings"
```

**config**
the `config.yaml` is as follow：
```yaml
# Definition of nodes
peer1: &peer1
  addr: peer0.org1.example.com:7051
  tls_ca_cert: /config/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem
  org: org1

peer2: &peer2
  addr: peer0.org2.example.com:9051
  tls_ca_cert: /config/fabric-samples/test-network/organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem
  org: org2

orderer1: &orderer1
  addr: orderer.example.com:7050
  tls_ca_cert: /config/fabric-samples/test-network/organizations/ordererOrganizations/example.com/msp/tlscacerts/tlsca.example.com-cert.pem
  org: org1

policyFile: /config/andLogic.rego
# Nodes to interact with
endorsers:
  - *peer1
# we might support multi-committer in the future for more complex test scenario,
# i.e. consider tx committed only if it's done on >50% of nodes. But for now,
# it seems sufficient to support single committer.
committers: 
 - *peer1
 - *peer2

commitThreshold: 1

orderer: *orderer1

# Invocation configs
channel: mychannel
chaincode: basic
args:
  - GetAllAssets
mspid: Org1MSP
private_key: /config/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk
sign_cert: /config/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem
num_of_conn: 10
client_per_conn: 10
```

And I have checked the logs on Peer0.org1.example.com，I'm sure Tape has submited some transactions.

**And also**
I also try the tape in terminal with the same config: （just change the path of certs and keys）
```bash
$ ./tape -c config.yaml -n 100
Time     0.05s	Block      6	Tx     10	 
Time     0.06s	Block      7	Tx     10	 
Time     0.07s	Block      8	Tx     10	 
Time     0.08s	Block      9	Tx     10	 
Time     0.09s	Block     10	Tx     10	 
Time     0.10s	Block     11	Tx     10	 
Time     0.10s	Block     12	Tx     10	 
Time     0.11s	Block     13	Tx     10	 
Time     0.12s	Block     14	Tx     10	 
Time     0.13s	Block     15	Tx     10	 
tx: 100, duration: 132.100957ms, tps: 756.996787
```
**However, it seems to be working properly!**
I really don't know how to solve this problem, anyone can help me?
Thanks so much!
