### ISSUE TITLE
Communicate with peer by proxy

### ISSUE THREAD

**Issue by iceriverdog** [Hyperledger-TWGC/tape#79]
HI sir，

How to Communicate with peer by proxy using your Tape？ thank you！
Like this：
```yaml
peers:
  peer0.adminorg.544330u:
    url: grpcs://181.71.124.24:30062
    grpcOptions:
      ssl-target-name-override: nginx.bc9seqlghk0u.baas
      grpc.primary_user_agent: /peer0-adminorg.bceqlghk0u
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/cert/nginx.bc9qlghk0u.baas.pem
```
